config/routes.rb
SimpleBanking::Application.routes.draw do

  post "/members" => "members#create"

  devise_for :members

  get "dashboard/index"

  devise_for :users

  resources :members do

  end

  resources :accounts do
    member do
      post :unlock
      post :lock
      get  :passbook
    end
  end

  resources :cash_collections do
    get :autocomplete_account_name, :on => :collection
  end

   root :to => 'dashboard#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Co-Operative Banking</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render :file => 'layouts/upper_navigation' %>
  <% render :file => 'layouts/bank_navigation' if current_member %>
  <%= render :file => 'layouts/roles_navigation' %>
  <p class="notice"><%= notice %></p>
  <p class="alert_message"><%= alert %></p>

</head>
<body>

 <%= yield %>

</body>
<footer class="footer"><p> copyright &copy; co-operative banking 2012 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Powered by <a href="sites.google.com/site/r2solution/">RealRadiantSolution</a></p></footer>
</html>

app/views/layouts/bank_navigation.html.erb
<% if current_user %>
<div class="tabbable">
  <ul class="nav nav-tabs">
    <li class= <%= params["controller"] == 'accounts' ? "active" : '' %>><%= link_to "Accounts", accounts_path %></li>
    <li class= <%= params["controller"] == 'members' ? "active" : '' %>><%= link_to "Members", members_path %></li>
    <li class= <%= params["controller"] == 'cash_collections' ? "active" : '' %>><%= link_to "Cash Collection", cash_collections_path %></li>
    <li class= <%= params["controller"] == 'loans' ? "active" : '' %>><%= link_to "Loan", '#' %></li>
  </ul>
</div>
<% end %>

app/views/layouts/roles_navigation.html.erb
<div class="navbar top-bar">
  <div class="navbar-inner">
    <a class="brand" href="#">Co-Operative Banking </a>
    <ul class="nav">
      <% if current_member %>
        <% case current_member.type.to_i %>
        <% when 0 %>
        <%= render :file => 'layouts/roles/super_admin' %>
        <% when 1 %>
        <%= render :file => 'layouts/roles/finance_admin' %>
        <% when 2 %>
        <%= render :file => 'layouts/roles/loan_admin' %>
        <% when 3 %>
        <%= render :file => 'layouts/roles/collection_admin' %>
        <% when 4 %>
        <%= render :file => 'layouts/roles/collection_staff' %>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

app/views/layouts/upper_navigation.html.erb
  <div class="navbar top_bar">
    <ul class="pull-right upper-nav">
      <% if user_signed_in? %>
      Welcome, <%= link_to current_user.email, edit_user_registration_path %> |
      <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
      <% elsif member_signed_in? %>
      Welcome, <%= link_to current_member.email, edit_member_path(current_member) %> |
      <%= link_to 'Logout', destroy_member_session_path, :method=>'delete' %>
      <% else %>
      <%= link_to 'MemberLogin', new_member_session_path %>
      <% end %>
    </ul>
  </div>