config/routes.rb
SimpleBanking::Application.routes.draw do

  post "/members" => "members#create"

  devise_for :members

  get "dashboard/index"

  devise_for :users

  resources :members do

  end

  resources :accounts do
    member do
      post :unlock
      post :lock
      get  :passbook
    end
  end

  resources :cash_collections do
    get :autocomplete_account_name, :on => :collection
  end

   root :to => 'dashboard#index'

end

app/models/member.rb
# == Schema Information
#
# Table name: members
#
#  id                     :integer          not null, primary key
#  user_name              :string(255)
#  type                   :string(255)
#  profile_id             :integer
#  status                 :string(255)      default("joined")
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0)
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :string(255)
#  last_sign_in_ip        :string(255)
#

# == Schema Information
#
# Table name: members
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  type       :string(255)      not null
#  profile_id :integer
#  status     :string(255)      default("joined")
#  email      :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
class Member < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable#,:registerable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  attr_accessible :user_name, :profile_id, :status, :type
  has_one :profile
  has_many :cash_collections
  self.inheritance_column = :_type_disabled

  ROLES = [["Super Admin", 0],["Finance Admin", 1],["Loan Admin",2],["Collection Admin",3],["Normal Staff",4]]

  def full_name
    @profile = self.profile
    if @profile
      @fullname = "#{@profile.fname} #{@profile.mname} #{@profile.lname}"
    end
    full_name = @fullname ? @fullname : self.user_name
  end

  def is_super_admin?
    type == "0"
  end

  def is_finance_admin?
    type == "1"
  end

  def is_loan_admin?
    type == "2"
  end

  def is_collection_admin?
    type == "3"
  end

  def is_collection_staff?
    type == "4"
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_filter :authenticate_member!
  before_filter :check_existance_of_profile, :only => [:show]

  def index
    @members = Member.all.to_a
  end

  def new
    @member = Member.new
  end

  def create
    member_data =  params['member'].except('profile')
    profile_data = params['member']['profile']
    @member = Member.new(member_data)
    Member.transaction do
      @member.save
      @profile = Profile.create(profile_data.merge({:member_id => @member.id}))
      @member.profile = @profile
      @member.save
    end
    respond_to do |format|
      if Member.last == @member
        format.html { redirect_to members_path, notice: 'Member created successfully!'}
      else
        format.html { render action: "new" }
      end
    end
  end

  def show
    @member = Member.find(params['id'])
    @profile = @member.profile
    @collections = @member.cash_collections
    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  def edit
    @member = Member.find(params['id'])
  end

  def update
    @member = Member.find(params['id'])
    member_data =  params['member'].except('profile')
    profile_data = params['member']['profile']
    @member.update_attributes(member_data)
    Member.transaction do
      @member.save
      @profile = Profile.create(profile_data.merge({:member_id => @member.id}))
      @member.profile = @profile
      @member.save
    end
    respond_to do |format|
      if Member.last == @member
        format.html { redirect_to members_path, notice: 'Member created successfully!'}
      else
        format.html { render action: "new" }
      end
    end
  end

  def destroy
    @member = Member.find(params['id'])
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_path, notice: 'Member deleted successfully!' }
    end
  end

  private

  def check_existance_of_profile
    if current_member
      member = current_member ||  Member.find(params["id"])
      unless member.profile
        redirect_to edit_member_path(member)
      end
    end
  end
end

app/views/members/_form.html.erb
<div class="box_show" >
  <%= form_for @member, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="informatio_name"> Step 1: Account/Login Information: </div>
  <div class="control-group">
    <%= f.label :user_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :user_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :password, :class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password, :class => 'text_field' %>
    </div>
  </div>

  <div class="control-group">
    <%= f.label :password_confirmation,:class => 'control-label' %>
    <div class="controls">
      <%= f.password_field :password_confirmation, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :role, :class => 'control-label' %>
    <div class="controls">
     <%= f.select(:type, options_for_select(Member::ROLES, :selected => params[:type]), { :include_blank => true }) %>
   </div>
 </div>
 <div class="control-group">
  <%= f.fields_for :profile do |pf| %>
  <%####################################################################%>
  <div class="informatio_name">Step 2: Personal Information: </div>
  <div class="control-group">
    <%= pf.label :first_name, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :fname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :middle_name, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :mname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :last_name, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :lname, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :father_name, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :father_name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :date_of_birth, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :dob, :class => 'text_field','data-behaviour' => 'datepicker' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :approximate_age, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :age, :class => 'numeric_field' %>
    </div>
  </div>
  <div class="informatio_name"> Address Information: </div>
  <div class="control-group">
    <%= pf.label :district, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :district, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :zone, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :zone, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :VDC, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :mcp, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :ward_no, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :ward_no, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :phone, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :phone, :class => 'numeric_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :occupation, :class => 'control-label' %>
    <div class="controls">
      <%= pf.text_field :occupation, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= pf.label :maritial_status, :class => 'control-label' %>
    <div class="controls">
      <%= pf.select(:maritial_status, options_for_select(Profile::MARITIAL_STATUS, :selected => params[:maritial_status])) %>
    </div>
  </div>
  <div class="informatio_name"> Step 3: Account Verification </div>
  <div class="control-group">
    <%= pf.label :verification_type, :class => 'control-label' %>
    <div class="controls">
     <%= pf.select(:verification_type, options_for_select(Profile::VERIFIED_BY,:selected => params[:verification_type] )) %>
   </div>
 </div>
 <div class="control-group">
  <%= pf.label :verification_id, :class => 'control-label' %>
  <div class="controls">
    <%= pf.text_field :verification_id, :class => 'text_field' %>
  </div>
</div>
<div class="control-group">
  <%= pf.label :your_recent_photo, :class => 'control-label' %>
  <div class="controls">
    <%= pf.file_field :image %>
  </div>
</div>
<%####################################################################%>
<% end %>
</div>

<div class="form-actions">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
  members_path, :class => 'btn' %>
</div>
<% end %>
</div>

app/views/members/edit.html.erb
<%= render :partial => 'form' %>

app/views/members/index.html.erb
<%= link_to "Add a new staff", new_member_path, :class => 'btn btn-primary pull-right' %>
<div class="box_show" >
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Member Id.</th>
        <th>Created At</th>
        <th>UserName</th>
        <th>Email</th>
        <th>Type</th>
        <th>Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @members.each do |member| %>
      <tr>
        <td><%= link_to member.id, member_path(member) %></td>
        <td><%= member.created_at.strftime("%b %d, %Y") %></td>
        <td><%= member.user_name %></td>
        <td><%= member.email %></td>
        <td><%= member.type %></td>
        <td><%= member.status %></td>
        <td>
          <%= link_to "Fire this member.",
          member_path(member),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/members/new.html.erb
<%= render :partial => 'form' %>

app/views/members/show.html.erb
<div class="box_show">
  <div class="box_content">
    <h4><%= @member.full_name %></h4>
    <div>
      <strong>Son of: </strong> <%= @profile.father_name %>
    </div>
    <div class="profile_image">
      <%= image_tag @profile.image_url(:thumb) if @profile.image? %>
    </div>
    <div>
      <strong>Address: </strong>
      <%= @profile.district %>
      <%= @profile.ward_no %>
      <%= @profile.zone %>
    </div>
    <div><strong>Status: </strong><%= @member.status %></div>
    <div>
      <strong>Collections Stats:</strong>
      <div class="balance_stats">
        <% unless @collections.blank? %>
        <p>Last collection done on: <%= @collections.last.created_at.strftime("%b %d, %Y") %> </p>
        <p>Last collected amount: <%= @collections.last.amount %> </p>
        <p>Last collection done for: <%= @collections.last.account.full_name %> </p>
        <% end %>
      </div>
    </div>
  </div>
</div>