config/routes.rb
SimpleBanking::Application.routes.draw do

  post "/members" => "members#create"

  devise_for :members

  get "dashboard/index"

  devise_for :users

  resources :members do

  end

  resources :accounts do
    member do
      post :unlock
      post :lock
      get  :passbook
    end
  end

  resources :cash_collections do
    get :autocomplete_account_name, :on => :collection
  end

   root :to => 'dashboard#index'

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id         :integer          not null, primary key
#  name       :string(255)      not null
#  type       :string(255)      not null
#  profile_id :integer
#  status     :string(255)
#  balance_id :integer
#  email      :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Account < ActiveRecord::Base
  attr_accessible :balance_id, :email, :name, :profile_id, :status, :type
  has_one :profile
  has_one :balance
  has_many  :cash_collections
  self.inheritance_column = :_type_disabled
  TYPE = [["Normal", 0],["Saving", 1],["Current",2]]

  def full_name
    @profile = self.profile
    if @profile
      @fullname = "#{@profile.fname} #{@profile.mname} #{@profile.lname}"
    end
    full_name = @fullname ? @fullname : self.name
  end

  def locked?
    status == 'locked'
  end

  def lock!
    update_attribute(:status, 'locked')
  end

  def unlock!
    update_attribute(:status, 'active')
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_member!

  def index
    @accounts = Account.all.to_a
  end

  def new
    @account = Account.new
    @profile = Profile.new
  end

  def create
    account_data =  params['account'].except('profile')
    profile_data = params['account']['profile']
    @account = Account.new(account_data)
    Account.transaction do
      @account.save
      @profile = Profile.create(profile_data.merge({:account_id => @account.id}))
      @account.profile = @profile
      @account.balance = Balance.create(:account_id => @account.id)
      @account.save!
    end
    respond_to do |format|
      if Account.last == @account
        format.html { redirect_to accounts_path, notice: 'Account created successfully!'}
      else
        format.html { render action: "new" }
      end
    end
  end

  def edit
    @account = Account.find(params['id'])
    @profile = @account.profile
  end

  def show
    @account = Account.find(params['id'])
    @profile = @account.profile
    @balance = @account.balance
    @collections = @account.cash_collections
    respond_to do |format|
      format.html # show.html.erb
      format.js
    end
  end

  def destroy
    @account = Account.find(params['id'])
    @account.destroy
    respond_to do |format|
      format.html { redirect_to accounts_path, notice: 'Account deleted successfully!' }
    end
  end

  def lock
    @account = Account.find(params['id'])
    @account.lock!
    redirect_to :back, :notice => "Account locked successfully"
  end

  def unlock
    @account = Account.find(params['id'])
    @account.unlock!
    redirect_to :back, :notice => "Account unlocked successfully"
  end

  def passbook
    @account = Account.find(params['id'])
    @passbook_data = @account.cash_collections
    if @passbook_data.present?
      respond_to do |format|
        format.html
      end
    else
      redirect_to :back, :alert => "There is no passbook for this account."
    end
  end
end

app/views/accounts/_form.html.erb
<div class="box_show" >
  <%= form_for @account, :html => { :multipart => true, :class => 'form-horizontal' } do |f| %>
  <div class="informatio_name"> Step 1: Basic Information: </div>
  <div class="control-group">
    <%= f.label :account_name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :account_type, :class => 'control-label' %>
    <div class="controls">
      <%= f.select(:type, options_for_select(Account::TYPE, :selected => params[:type]), { :include_blank => true }) %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :email, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :email, :class => 'text_field' %>
    </div>
  </div>

  <div class="informatio_name"> Step 2: Personal Information: </div>
  <div class="control-group">
    <%= f.fields_for :profile do |pf| %>
    <%####################################################################%>
    <div class="control-group">
      <%= pf.label :first_name, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :fname, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :middle_name, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :mname, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :last_name, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :lname, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :father_name, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :father_name, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :date_of_birth, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :dob, :class => 'text_field','data-behaviour' => 'datepicker' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :approximate_age, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :age, :class => 'numeric_field' %>
      </div>
    </div>
    <div class="informatio_name"> Address Information: </div>
    <div class="control-group">
      <%= pf.label :zone, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :zone, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :district, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :district, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :VDC, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :mcp, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :ward_no, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :ward_no, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :phone, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :phone, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :occupation, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :occupation, :class => 'text_field' %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :maritial_status, :class => 'control-label' %>
      <div class="controls">
        <%= pf.select(:maritial_status, options_for_select(Profile::MARITIAL_STATUS, :selected => params[:maritial_status])) %>
      </div>
    </div>
    <div class="informatio_name"> Step 3: Account Verification </div>
    <div class="control-group">
      <%= pf.label :verification_type, :class => 'control-label' %>
      <div class="controls">
        <%= pf.select(:verification_type, options_for_select(Profile::VERIFIED_BY,:selected => params[:verification_type] )) %>
      </div>
    </div>
    <div class="control-group">
      <%= pf.label :verification_id, :class => 'control-label' %>
      <div class="controls">
        <%= pf.text_field :verification_id, :class => 'text_field' %>
      </div>
    </div>

    <div class="control-group">
      <%= pf.label :your_recent_photo, :class => 'control-label' %>
      <div class="controls">
        <%= pf.file_field :image %>
      </div>
    </div>
    <%####################################################################%>
    <% end %>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to 'cancle', accounts_path, :class => 'btn' %>
  </div>
  <% end %>
</div>

app/views/accounts/edit.html.erb
<%= render :partial => 'form' %>

app/views/accounts/index.html.erb
<%= link_to "Add New Account", new_account_path, :class => 'btn btn-primary pull-right' %>
<div class="box_show" >
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Account No.</th>
        <th>Created At</th>
        <th>Name</th>
        <th>Email</th>
        <th>Type</th>
        <th>Status</th>
        <th>Balance</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @accounts.each do |account| %>
      <tr>
        <td><%= link_to account.id, account_path(account) %></td>
        <td><%= account.created_at.strftime("%b %d, %Y") %></td>
        <td><%= account.name %></td>
        <td><%= account.email %></td>
        <td><%= account.type %></td>
        <td><%= account.status %></td>
        <td><%= account.balance.amount %></td>
        <td>
          <%= link_to "Passbook", passbook_account_path(account),:method => :get, :class => 'btn btn-mini btn-action' %>
          <%= link_to "Delete",
          account_path(account),
          :method => :delete,
          :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
          :class => 'btn btn-mini btn-danger' %>

          <% if account.locked? %>
          <%= link_to "Unlock", unlock_account_path(account),:method => :post, :class => 'btn btn-mini btn-action' %>
          <% else %>
          <%= link_to "Lock", lock_account_path(account),:method => :post, :class => 'btn btn-mini btn-action' %>
          <% end %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/new.html.erb
<%= render :partial => 'form' %>

app/views/accounts/passbook.html.erb
<div class="box_show" >
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Date</th>
        <th>Description</th>
        <th>Amount Deposited</th>
        <th>Collection Type</th>
        <th>Total Amount</th>
        <th>Collected By</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% total_amount = 0 %>
      <% @passbook_data.each do |collection| %>
      <tr>
        <td><%= collection.created_at.strftime("%b %d, %Y") %></td>
        <td><%= collection.description %></td>
        <td><%= amount = collection.amount %></td>
        <td><%= type = collection.type %></td>
        <% type == "debit" ? (total_amount += amount) : (total_amount -= amount)  %>
        <td><%= total_amount %></td>
        <td><%= collection.collected_by %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/accounts/show.html.erb
<div class="box_show">
  <div class="box_content">
    <h4><%= @account.full_name %></h4>
    <div>
      <strong>Son of: </strong> <%= @profile.father_name %>
    </div>
    <div class="profile_image">
      <%= image_tag @profile.image_url(:thumb) if @profile.image? %>
    </div>
    <div>
      <strong>Address: </strong>
      <%= @profile.district %>
      <%= @profile.ward_no %>
      <%= @profile.zone %>
    </div>
    <div><strong>Status: </strong><%= @account.status %></div>
    <div>
      <strong>Balance:</strong>
      <div class="balance_stats">
        <p>Current Amount: <%= @balance.amount%> </p>
        <% unless @collections.blank? %>
        <p>Last collection done on: <%= @collections.last.created_at.strftime("%b %d, %Y") %> </p>
        <p>Last collected amount: <%= @collections.last.amount %> </p>
        <p>Last collection done by: <%= @collections.last.collected_by %> </p>
        <% end %>
      </div>
    </div>
  </div>
</div>